### ISSUE TITLE
Some state data is missing

### ISSUE THREAD

**Issue by scherbakovdmitri** [brendensm/CDCPLACES#3]
Great package, but some states data is missing, for example TX works but FL fails:
`cap_counties <- get_places(
                            geography='county',
                           state = "FL",
                               geometry = F)`

Error in FUN(X[[i]], ...) : 
Please enter a valid US State name.

**Comment by scherbakovdmitri** [comment]
Seems Florida is missing in original data

**Comment by scherbakovdmitri** [comment]
Seems Florida is missing in CDC data

**Comment by brendensm** [comment]
Thanks for pointing this out @scherbakovdmitri. This was an error on my end. I have updated the repository with a fix. If you remove the package and reinstall with devtools::install_github it should work. It will be updated on CRAN in a few days. Please let me know if you run into any further issues!
